print("CUSTOMER DETAILS")
x=str(input(name))
y=int(input(age))
z=tuple(input(address))
k=str(input(preference))
j=int(input(no in family))
g=dict(input(phone))
y=int(input(sex))
v=float(input(heigth))
details=(x+y+z+k+j+g+y+v)
print("details")
